[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "_tag.children[2].children[1].config.colour = G.C.UI.TEXT_LIGHT"
position = "after"
payload = '''
    _tag.children[3].config.button = 'skip_blind'
    _tag.config.outline_colour = adjust_alpha(G.C.BLUE, 0.5)
    _tag.children[3].config.hover = true
    _tag.children[3].config.colour = G.C.RED
    _tag.children[3].children[1].config.colour = G.C.UI.TEXT_LIGHT
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "_tag.children[2].children[1].config.colour = G.C.UI.TEXT_INACTIVE"
position = "after"
payload = '''
    _tag.children[3].config.button = nil
    _tag.children[3].config.hover = false
    _tag.children[3].config.colour = G.C.UI.BACKGROUND_INACTIVE
    _tag.children[3].children[1].config.colour = G.C.UI.TEXT_INACTIVE
'''
match_indent = true